# Generated by Django 3.1.3 on 2021-08-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('descr',),
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grupo',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='SessaoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Descrição')),
                ('regras', models.CharField(default='Sem Regras', max_length=1000, null=True, verbose_name='Regras')),
                ('ativo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
            ],
            options={
                'verbose_name': 'sessao',
                'verbose_name_plural': 'sessões',
                'ordering': ('descr',),
            },
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, verbose_name='Apelido')),
                ('nome', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.grupo')),
            ],
            options={
                'verbose_name': 'publico',
                'ordering': ('grupo', 'nick'),
            },
        ),
    ]
