# Generated by Django 3.1.3 on 2021-08-14 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoevento',
            name='datafim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Encerramento'),
        ),
        migrations.AddField(
            model_name='sessaoevento',
            name='dataini',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Inicio'),
        ),
    ]
