# Generated by Django 3.1.3 on 2021-08-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grupo',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='sessaoevento',
            name='datafim',
            field=models.DateField(auto_now=True, verbose_name='Data Encerramento'),
        ),
        migrations.AddField(
            model_name='sessaoevento',
            name='dataini',
            field=models.DateField(auto_now=True, verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descr',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='descr',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.evento'),
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, verbose_name='Apelido')),
                ('nome', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.grupo')),
            ],
            options={
                'verbose_name': 'publico',
                'ordering': ('grupo', 'nick'),
            },
        ),
    ]
