# Generated by Django 3.1.3 on 2021-08-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210811_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoevento',
            name='regras',
            field=models.TextField(blank=True, default='Sem Regras', max_length=1000, null=True, verbose_name='Regras'),
        ),
    ]
