# Generated by Django 3.1.3 on 2021-08-15 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20210814_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publico',
            options={'ordering': ('nick',), 'verbose_name': 'publico'},
        ),
        migrations.RemoveField(
            model_name='publico',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='publico',
            name='nome',
        ),
        migrations.AddField(
            model_name='publico',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='E-Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publico',
            name='publico_filho',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='eventos.publico', verbose_name='Publico Filho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publico',
            name='nick',
            field=models.CharField(max_length=10, verbose_name='Publico'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
