# Generated by Django 3.1.3 on 2021-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_sessaoevento_regras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoevento',
            name='regras',
            field=models.CharField(blank=True, default='Sem Regras', max_length=1000, null=True, verbose_name='Regras'),
        ),
    ]
