# Generated by Django 3.1.3 on 2021-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20210814_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoevento',
            name='datafim',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Encerramento'),
        ),
        migrations.AddField(
            model_name='sessaoevento',
            name='dataini',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='descr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='regras',
            field=models.TextField(default='Sem Regras', max_length=4000, verbose_name='Regras'),
        ),
    ]
