# Generated by Django 3.1.3 on 2021-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210816_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoevento',
            name='datafim',
            field=models.DateField(null=True, verbose_name='Data Encerramento'),
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='dataini',
            field=models.DateField(null=True, verbose_name='Data Inicio'),
        ),
    ]
