# Generated by Django 3.1.3 on 2021-08-20 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0007_auto_20210816_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessaoevento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessaoevento',
            name='descr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descrição da Sessão'),
        ),
    ]
