version: "3.3"

services: 
  db:
    image: postgres
    #container_name: postgresql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres!
    ports: 
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  edt:
    image: ghcr.io/linuxserver/code-server
    #container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
      - PASSWORD=salvador #optional
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=egito #optional
      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.salvador.eti
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/:/home/app/web
      - ${HOME}/.ssh:/home/app/.ssh
      - ${HOME}/adriano:/home/app/adriano
    ports:
      - 8443:8443
    restart: unless-stopped

  web:
    build: .
    #container_name: python
    environment: 
      - POSTGRES_HOST=db
      - PYTHONPATH=/usr/bin
      - APP=Dj Aprendiz
    volumes: 
      - ${PWD}/:/home/app/web
    command: python manage.py runserver 0.0.0.0:8080
    working_dir: /home/app/web
    #ports: 
    #  - 8080:8080
    depends_on: 
      - db

  nginx:
    #container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ${PWD}/static:/home/app/web/static
      - ${PWD}/staticfiles:/home/app/web/staticfiles
      - ${PWD}/media:/home/app/web/media
    depends_on:
      - web

#  web_a:
#    image: pystore_web:latest
#    environment: 
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=contratos
#      - PYTHONPATH=/usr/bin
#      - APP=Dj Aprendiz
#    volumes: 
#      - ${HOME}/adriano:/home/app/web
#    command: python manage.py runserver 0.0.0.0:8080
#    working_dir: /home/app/web
#    ports: 
#      - 8082:8080
#    depends_on: 
#      - web
#      - db
#
volumes:
  postgres_data:
