version: "3.3"

services: 
  db:
    image: postgres
    #container_name: postgresql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres!
    ports: 
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  edt:
    image: ghcr.io/linuxserver/code-server
    #container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
      - PASSWORD=salvador #optional
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=egito #optional
      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.salvador.eti
    volumes:
      - ${HOME}/config:/config
      - ${HOME}/pystore:/home/app/web
    ports:
      - 8443:8443
    restart: unless-stopped

  web:
    build: .
    #container_name: python
    environment: 
      - POSTGRES_HOST=db
      - PYTHONPATH=/usr/bin
    volumes: 
      - ${HOME}/pystore:/home/app/web
      - ${HOME}/pystore/static:/home/app/web/static
      - ${HOME}/pystore/media:/home/app/web/media
    command: python manage.py runserver 0.0.0.0:8080
    working_dir: /home/app/web
    #ports: 
    #  - 8080:8080
    depends_on: 
      - db

  nginx:
    #container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ${HOME}/pystore/static:/home/app/web/static
      - ${HOME}/pystore/media:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data:
#  portainer_data:
