# Generated by Django 3.1.3 on 2021-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_auto_20210803_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
