# Generated by Django 3.1.3 on 2021-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20210805_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
