# Generated by Django 3.1.3 on 2021-08-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_auto_20210805_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
