# Generated by Django 3.1.3 on 2021-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_auto_20210806_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='fornecedor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
