# Generated by Django 3.1.3 on 2021-08-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20210808_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupos',
            new_name='Grupo',
        ),
        migrations.RenameModel(
            old_name='Jogadores',
            new_name='Publico',
        ),
        migrations.AlterModelOptions(
            name='publico',
            options={'ordering': ('grupo', 'nick'), 'verbose_name': 'publico'},
        ),
    ]
